# Generated by Django 3.0.8 on 2020-08-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SG_DIC_PLANTSTATIONTYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.IntegerField(db_index=True, unique=True)),
                ('NAME', models.CharField(max_length=64)),
                ('EFFECT_FLAG', models.CharField(choices=[('Y', '可用'), ('N', '弃用')], max_length=1)),
            ],
            options={
                'verbose_name_plural': '场站基础信息表',
            },
        ),
        migrations.CreateModel(
            name='SG_DIC_REGION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.IntegerField(db_index=True, unique=True)),
                ('NAME', models.CharField(max_length=64)),
                ('EFFECT_FLAG', models.CharField(choices=[('Y', '可用'), ('N', '弃用')], max_length=1)),
            ],
            options={
                'verbose_name_plural': '场站基础信息表',
            },
        ),
        migrations.CreateModel(
            name='SG_DIC_VOLTAGETYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.IntegerField(db_index=True, unique=True)),
                ('NAME', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '场站基础信息表',
            },
        ),
        migrations.CreateModel(
            name='SG_CON_PLANT_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=64)),
                ('NAME', models.CharField(max_length=128, unique=True)),
                ('VIRTUAL', models.BooleanField(default=False)),
                ('MAX_VOLTAGE_TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dudu.SG_DIC_VOLTAGETYPE', to_field='CODE')),
                ('PLANT_TYPE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dudu.SG_DIC_PLANTSTATIONTYPE', to_field='CODE')),
                ('REGION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dudu.SG_DIC_REGION', to_field='CODE')),
            ],
            options={
                'verbose_name_plural': '场站基础信息表',
            },
        ),
    ]
