# Generated by Django 2.2 on 2020-08-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sg_con_plant_b',
            table='sg_con_plant_b',
        ),
        migrations.AlterModelTable(
            name='sg_dic_plantstationtype',
            table='sg_dic_plantstationtype',
        ),
        migrations.AlterModelTable(
            name='sg_dic_region',
            table='sg_dic_region',
        ),
        migrations.AlterModelTable(
            name='sg_dic_voltagetype',
            table='sg_dic_voltagetype',
        ),
    ]
