# Generated by Django 2.2 on 2020-08-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dudu', '0002_auto_20200811_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sg_dic_plantstationtype',
            options={'verbose_name_plural': '发电类型表'},
        ),
        migrations.AlterModelOptions(
            name='sg_dic_region',
            options={'verbose_name_plural': '区域表'},
        ),
        migrations.AlterModelOptions(
            name='sg_dic_voltagetype',
            options={'verbose_name_plural': '电压等级表'},
        ),
        migrations.AlterField(
            model_name='sg_con_plant_b',
            name='MAX_VOLTAGE_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dudu.SG_DIC_VOLTAGETYPE', to_field='CODE', verbose_name='并网电压等级'),
        ),
        migrations.AlterField(
            model_name='sg_con_plant_b',
            name='NAME',
            field=models.CharField(max_length=128, unique=True, verbose_name='场站名称'),
        ),
        migrations.AlterField(
            model_name='sg_con_plant_b',
            name='PLANT_TYPE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dudu.SG_DIC_PLANTSTATIONTYPE', to_field='CODE', verbose_name='发电类型'),
        ),
        migrations.AlterField(
            model_name='sg_con_plant_b',
            name='REGION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dudu.SG_DIC_REGION', to_field='CODE', verbose_name='电场所属区域'),
        ),
        migrations.AlterField(
            model_name='sg_con_plant_b',
            name='VIRTUAL',
            field=models.BooleanField(default=False, verbose_name='是否虚拟电厂'),
        ),
        migrations.AlterField(
            model_name='sg_dic_plantstationtype',
            name='CODE',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='发电类型id'),
        ),
        migrations.AlterField(
            model_name='sg_dic_plantstationtype',
            name='EFFECT_FLAG',
            field=models.CharField(choices=[('Y', '可用'), ('N', '弃用')], max_length=1, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='sg_dic_plantstationtype',
            name='NAME',
            field=models.CharField(max_length=64, verbose_name='发电类型名称'),
        ),
        migrations.AlterField(
            model_name='sg_dic_region',
            name='CODE',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='区域id'),
        ),
        migrations.AlterField(
            model_name='sg_dic_region',
            name='EFFECT_FLAG',
            field=models.CharField(choices=[('Y', '可用'), ('N', '弃用')], max_length=1, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='sg_dic_region',
            name='NAME',
            field=models.CharField(max_length=64, verbose_name='区域名称'),
        ),
        migrations.AlterField(
            model_name='sg_dic_voltagetype',
            name='CODE',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='电压等级id'),
        ),
        migrations.AlterField(
            model_name='sg_dic_voltagetype',
            name='NAME',
            field=models.CharField(max_length=64, verbose_name='电压等级名称'),
        ),
    ]
